### PR TITLE
Make code smaller

### PR DESCRIPTION
**Pull request by alwwwd**

### CODE REVIEW

**Comment by c22dev** [comment]
Hi !
I really like your SettingsView Credits implementation, tho I don't understand the point of the changes you made on ApplicationVIew... no real win here imo. Would you mind maybe reverting your changes on this view ?

Anyway, thanks a ton for your contribution!

**Comment by alwwwd** [comment]
I try migrating to mvvm but i see signing bugs and i move only var's and let's to ViewModel

**Comment by c22dev** [comment]
I don't think its really impactful atm in my opinion, sorry

**Comment by alwwwd** [comment]
> Hi ! I really like your SettingsView Credits implementation, tho I don't understand the point of the changes you made on ApplicationVIew... no real win here imo. Would you mind maybe reverting your changes on this view ?
> 
> Anyway, thanks a ton for your contribution!
Reverted and added new fixes

**Comment by alwwwd** [comment]
> Hi ! I really like your SettingsView Credits implementation, tho I don't understand the point of the changes you made on ApplicationVIew... no real win here imo. Would you mind maybe reverting your changes on this view ?
> 
> Anyway, thanks a ton for your contribution!

reverted and added new fixes

**Pull request closed without merging**
